# Generated by Django 3.2.13 on 2022-11-10 06:37

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('produt_thum_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/thum')),
                ('produt_desc_img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/thum')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('sales_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
