# Generated by Django 3.2.13 on 2022-11-10 06:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='produt_desc_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='produt_thum_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images'),
        ),
    ]
