# Generated by Django 3.2.13 on 2022-11-10 07:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221110_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('메밀', '메밀'), ('닭고기', '닭고기'), ('대두', '대두'), ('땅콩', '땅콩'), ('쇠고기', '쇠고기'), ('난류', '난류'), ('새우', '새우'), ('우유', '우유'), ('아황산류', '아황산류'), ('조개류', '조개류'), ('오징어', '오징어'), ('복숭아', '복숭아'), ('토마토', '토마토'), ('고등어', '고등어'), ('돼지고기', '돼지고기'), ('호두', '호두'), ('밀', '밀'), ('게', '게')], default=1, max_length=62),
            preserve_default=False,
        ),
    ]
