# Generated by Django 3.2.13 on 2022-11-10 07:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('밀', '밀'), ('호두', '호두'), ('우유', '우유'), ('오징어', '오징어'), ('조개류', '조개류'), ('토마토', '토마토'), ('새우', '새우'), ('땅콩', '땅콩'), ('아황산류', '아황산류'), ('복숭아', '복숭아'), ('쇠고기', '쇠고기'), ('대두', '대두'), ('메밀', '메밀'), ('난류', '이 제품은 계금류,난류에 대한 알러지 성분이 포함되어 있습니다.'), ('돼지고기', '돼지고기'), ('게', '게'), ('닭고기', '닭고기'), ('고등어', '고등어')], max_length=62),
        ),
    ]
