# Generated by Django 3.2.13 on 2022-11-10 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('밀', '밀'), ('쇠고기', '쇠고기'), ('호두', '호두'), ('닭고기', '닭고기'), ('우유', '우유'), ('토마토', '토마토'), ('돼지고기', '돼지고기'), ('새우', '새우'), ('조개류', '조개류'), ('대두', '대두'), ('게', '게'), ('고등어', '고등어'), ('복숭아', '복숭아'), ('오징어', '오징어'), ('아황산류', '아황산류'), ('땅콩', '땅콩'), ('메밀', '메밀'), ('난류', '난류')], max_length=62),
        ),
    ]
