# Generated by Django 3.2.13 on 2022-11-10 07:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_allergy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('복숭아', '복숭아'), ('대두', '대두'), ('게', '게'), ('조개류', '조개류'), ('호두', '호두'), ('토마토', '토마토'), ('땅콩', '땅콩'), ('메밀', '메밀'), ('돼지고기', '돼지고기'), ('밀', '밀'), ('난류', '난류'), ('오징어', '오징어'), ('새우', '새우'), ('닭고기', '닭고기'), ('고등어', '고등어'), ('아황산류', '아황산류'), ('우유', '우유'), ('쇠고기', '쇠고기')], max_length=62),
        ),
        migrations.AlterModelTable(
            name='product',
            table='상품',
        ),
    ]
