# Generated by Django 3.2.13 on 2022-11-10 08:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221110_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('밀', '밀'), ('새우', '새우'), ('쇠고기', '쇠고기'), ('복숭아', '복숭아'), ('조개류', '조개류'), ('토마토', '토마토'), ('게', '게'), ('호두', '호두'), ('우유', '우유'), ('오징어', '오징어'), ('고등어', '고등어'), ('메밀', '메밀'), ('돼지고기', '돼지고기'), ('땅콩', '땅콩'), ('난류', '난류'), ('대두', '대두'), ('닭고기', '닭고기'), ('아황산류', '아황산류')], max_length=62),
        ),
    ]
